language: groovy
sudo: required

before_install:
  - unzip ui/firefox-45.5.1-esr.zip -d ui
  - sudo pip install bzt

addons:
  apt:
    packages:
      - xvfb

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

script:
#  - mvn test
  - bzt performance.yml

#after_success:
#  - bash <(curl -s https://codecov.io/bash)

